import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navebar from "./components/navbar";
import Providers from "./providers";
import AppSessionProvider from "./SessionProvider";
// import { ThemeProvider } from "./components/them-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
   <html lang="en" suppressHydrationWarning>
  <body>
    <Providers>
       <AppSessionProvider>
  {children}
</AppSessionProvider>

    </Providers>
  </body>
</html>
  );
}

